const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const fs=require('node:fs');
let browser;
(async()=>{
  browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[],violations=[],manualReview=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.route(/^https?:/,r=>r.abort());
  await page.goto(pathToFileURL(path.resolve('index.html')).href);
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready.'));
  await page.evaluate(fs.readFileSync(require.resolve('axe-core/axe.min.js'),'utf8'));
  const scan=async name=>{
    const report=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa','best-practice']}}));
    for(const item of report.incomplete)manualReview.push({screen:name,id:item.id,targets:item.nodes.map(n=>n.target)});
    for(const v of report.violations)violations.push({screen:name,id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,reason:n.failureSummary}))});
    console.log(name+': '+report.violations.length+' accessibility violations');
  };
  await scan('Empty state');
  // Skip navigation is visible on focus and actually moves keyboard focus.
  await page.keyboard.press('Tab');
  assert.equal(await page.locator(':focus').textContent(),'Skip to font controls');
  await page.keyboard.press('Enter');assert.equal(await page.locator(':focus').getAttribute('id'),'google-font');
  await page.locator('.skip-links a').nth(1).focus();await page.keyboard.press('Enter');
  assert.equal(await page.locator(':focus').getAttribute('id'),'review-scroll');
  await page.locator('#upload').setInputFiles('fonts/SourceSerif4.ttf');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Loaded'));
  await scan('Size comparison');
  await page.locator('#font-summary summary').click();await scan('Font details');
  await page.locator('#font-summary summary').click();
  await page.locator('#comparison-size-tab').focus();await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator(':focus').getAttribute('id'),'comparison-overlay-tab');
  await scan('Overlay comparison');
  await page.locator('#size').evaluate(e=>{e.value=12;e.dispatchEvent(new Event('input',{bubbles:true}));});
  await scan('Overlay at minimum inspection size');
  await page.locator('#size').evaluate(e=>{e.value=48;e.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.locator('#comparison-overlay-tab').focus();await page.keyboard.press('Home');
  assert.equal(await page.locator('#comparison-size-tab').getAttribute('aria-selected'),'true');
  assert.equal(await page.getByRole('slider',{name:'Small-cap weight',exact:true}).count(),1);
  assert.equal(await page.getByRole('spinbutton',{name:'Small-cap weight',exact:true}).count(),1);
  assert.equal(await page.getByRole('slider',{name:'Text weight',exact:true}).count(),1);
  await page.locator('#weight').focus();const weight=+await page.locator('#weight').inputValue();
  await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Loaded'));
  assert(Math.abs(+await page.locator('#weight').inputValue()-weight-.1)<.001);
  assert.equal(await page.locator(':focus').getAttribute('id'),'weight','Rerender must preserve slider focus');
  await page.locator('#fit').focus();await page.keyboard.press('Enter');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Loaded'));
  assert.equal(await page.locator(':focus').getAttribute('id'),'fit','Refitting must restore button focus');
  await page.locator('#preview-tab').focus();await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator(':focus').getAttribute('id'),'outlines-tab');
  assert.equal(await page.locator('#preview-panel').getAttribute('aria-hidden'),'true');
  await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').getAttribute('id'),'review-scroll');
  await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').getAttribute('id'),'outlines-panel');
  await page.locator('#outlines-tab').click();await scan('Outlines');
  await page.locator('#research-tab').click();await scan('Research');
  const points=page.locator('#corpus-plot [data-category]');
  assert.equal(await page.locator('#corpus-plot [data-category][tabindex="0"]').count(),1);
  await points.first().focus();await page.keyboard.press('ArrowRight');
  assert.equal(await points.nth(1).getAttribute('tabindex'),'0');
  assert.equal(await page.locator('#corpus-detail').textContent(),await points.nth(1).getAttribute('aria-label'));
  await page.keyboard.press('End');assert.equal(await points.last().getAttribute('tabindex'),'0');
  await page.keyboard.press('Home');assert.equal(await points.first().getAttribute('tabindex'),'0');
  await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').getAttribute('id'),'corpus-table-region');
  assert.equal(await page.locator('#corpus-table thead th[scope="col"]').count(),12);
  assert.match(await page.locator('#corpus-table thead th').last().textContent(),/^Graph:/);
  assert.equal(await page.locator('#corpus-table tbody th[scope="row"]').count(),await points.count());
  assert.equal(await page.locator('#corpus-plot rect[data-category="serif"]').count(),await page.locator('#corpus-plot [data-category="serif"]').count());
  await page.locator('#preview-tab').click();await page.locator('#export-toggle').click();await scan('CSS export');
  await page.locator('#export-target').selectOption('typst');await scan('Typst export');
  await page.locator('#share').click();await scan('Share dialog');
  for(let i=0;i<6;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement===document.body||document.querySelector('#share-dialog').contains(document.activeElement)),'Modal must not focus background controls');}
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{}}}));
  await page.locator('#share-copy').click();await page.waitForFunction(()=>document.querySelector('#share-feedback').textContent==='Link copied.');
  await page.keyboard.press('Escape');assert.equal(await page.locator(':focus').getAttribute('id'),'share');
  await page.setViewportSize({width:320,height:800});await scan('320px viewport');
  await page.locator('#recipe-toggle').click();await scan('Mobile recipe controls');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px layout must not overflow horizontally');
  await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  await scan('200% text at 320px');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'200% text must reflow without page overflow');
  await page.evaluate(()=>document.documentElement.style.fontSize='');
  await page.setViewportSize({width:1440,height:1000});
  await page.emulateMedia({forcedColors:'active'});await scan('Forced colors');
  await page.locator('#share').focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');
  assert.notEqual(await page.locator('#share').evaluate(e=>getComputedStyle(e).outlineStyle),'none');
  await page.emulateMedia({forcedColors:'none'});
  await page.locator('#copy-typeset').click();
  await page.waitForFunction(()=>document.querySelector('#action-status').textContent==='Typesetting code copied.');
  assert.equal(await page.locator(':focus').getAttribute('id'),'copy-typeset');
  await page.locator('#google-font').fill('https://example.com/unavailable.ttf');
  await page.locator('#google-font').press('Enter');
  await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));
  assert.equal(await page.locator(':focus').getAttribute('id'),'google-font','Font loading errors must not lose input focus');
  assert.equal(await page.locator('#google-font').evaluate(e=>e.readOnly),false);
  await scan('Font loading error');
  await page.screenshot({path:'/tmp/smallcaps-accessible-desktop.png'});
  fs.writeFileSync(path.join(require('node:os').tmpdir(),'smallcaps-accessibility-review.json'),JSON.stringify({violations,manualReview},null,2));
  console.log(JSON.stringify(violations,null,2));
  assert.deepEqual(violations,[]);assert.deepEqual(errors,[]);
  await browser.close();console.log('Automated accessibility scans passed.');
})().catch(async error=>{console.error(error);await browser?.close();process.exitCode=1;});
