const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
let browser;
(async()=>{
  browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.resolve('index.html')).href);
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready.'));
  await page.locator('#upload').setInputFiles('fonts/SourceSans3.ttf');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Loaded'));
  assert.equal(await page.locator('#export-toggle').getAttribute('aria-expanded'),'false');
  assert.equal(await page.locator('#export-content').isVisible(),false);
  const collapsed=await page.locator('#review-scroll').evaluate(e=>e.clientHeight);
  assert((await page.locator('#export-dock').boundingBox()).height<60);
  await page.locator('#export-toggle').click();
  assert(await page.locator('#review-scroll').evaluate(e=>e.clientHeight)<collapsed-150);
  await page.locator('#export-toggle').press('Enter');
  assert.equal(await page.locator('#review-scroll').evaluate(e=>e.clientHeight),collapsed);
  assert.equal(await page.locator('#reading').count(),0);
  assert.equal(await page.locator('#size-ladder > .ladder-row:first-child .ladder-all-caps').textContent(),'The LORD is my shepherd');
  assert.equal(await page.locator('#size-ladder > .ladder-row:first-child .ladder-all-caps > *').count(),0);
  assert.equal(await page.locator('#size-ladder > .ladder-row:first-child .ladder-all-caps').evaluate(e=>getComputedStyle(e).transform),'none');
  assert.deepEqual(await page.locator('.ladder-row').first().locator('[data-preview-line]').evaluateAll(es=>es.map(e=>e.dataset.previewLine)),['all-caps','naive','calibrated','transformed','native']);
  assert.deepEqual(await page.locator('.ladder-row>.muted').allTextContents(),['48px','36px','32px','28px','24px','20px','18px','16px','14px','12px']);
  assert.deepEqual((await page.locator('.ladder-pair').first().locator('.caption').allTextContents()).slice(0,4),['All caps','Naive','Font-axis','Scaling']);
  const wordWidths=()=>page.locator('#size-ladder > .ladder-row:first-child .ladder-all-caps, #size-ladder > .ladder-row:first-child .ladder-naive .sc-word, #size-ladder > .ladder-row:first-child .ladder-calibrated .sc-word, #size-ladder > .ladder-row:first-child .ladder-transformed .sc-word, #size-ladder > .ladder-row:first-child .ladder-native .sc-word').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().width));
  const originalWidths=await wordWidths();
  await page.locator('#gap-out').fill('0.05');await page.locator('#gap-out').press('Enter');
  const adjustedWidths=await wordWidths();
  assert.equal(adjustedWidths[0],originalWidths[0]);
  for(let i=1;i<originalWidths.length;i++)assert(Math.abs(adjustedWidths[i]-originalWidths[i]-2.4)<.1,`Initial gap must affect comparison ${i}`);
  await page.locator('#gap-out').fill('0');await page.locator('#gap-out').press('Enter');
  assert(await page.locator('.ladder-pair .comparison-row').evaluateAll(es=>es.every(e=>getComputedStyle(e).borderBottomWidth==='0px'&&getComputedStyle(e).paddingTop==='0px'&&getComputedStyle(e).paddingBottom==='0px')));
  const panes=await page.evaluate(()=>{
    const sidebar=document.querySelector('#sidebar'),main=document.querySelector('#review-scroll');
    const before=main.scrollTop,top=main.getBoundingClientRect().top;
    sidebar.scrollTop=sidebar.scrollHeight;
    return {height:sidebar.clientHeight,scrollable:sidebar.scrollHeight>sidebar.clientHeight,sidebarScroll:sidebar.scrollTop,mainScroll:main.scrollTop-before,mainTop:main.getBoundingClientRect().top-top,documentHeight:document.documentElement.scrollHeight,viewport:innerHeight};
  });
  assert(panes.height>850&&panes.scrollable&&panes.sidebarScroll>0);
  assert.equal(panes.mainScroll,0);assert.equal(panes.mainTop,0);
  assert.equal(panes.documentHeight,panes.viewport);
  const sidebarTop=await page.locator('#sidebar').evaluate(e=>e.scrollTop);
  await page.locator('#review-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);
  assert.equal(await page.locator('#sidebar').evaluate(e=>e.scrollTop),sidebarTop);
  await page.locator('#export-toggle').click();
  await page.locator('#review-scroll').evaluate(e=>e.scrollTop=700);
  const beforeExport=await page.locator('#review-scroll').evaluate(e=>({top:e.scrollTop,html:e.innerHTML}));
  for(const mode of ['javascript','none','precomputed']) {
    await page.locator(`#width-${mode}`).click();
    assert.deepEqual(await page.locator('#review-scroll').evaluate(e=>({top:e.scrollTop,html:e.innerHTML})),beforeExport,'Export choices must leave the preview and its scroll position unchanged');
  }
  assert.match(await page.locator('#export-mode-note').innerText(),/only for the uppercase words in the preview above/);
  await page.locator('#width-unscaled').click();
  assert.equal(await page.locator('#width-method').inputValue(),'unscaled');
  assert.equal(await page.locator('#review-scroll').evaluate(e=>e.scrollTop),beforeExport.top);
  assert.doesNotMatch(await page.locator('#css-export').textContent(),/scaleX/);
  assert.equal(await page.locator('.selected-output').count(),0);
  assert.match(await page.locator('#export-mode-note').innerText(),/reusable with any words/);
  await page.locator('#width-precomputed').click();
  assert.equal(await page.locator('#review-scroll').evaluate(e=>e.scrollTop),beforeExport.top);
  assert.match(await page.locator('#css-export').textContent(),/scaleX/);
  await page.locator('#width-precomputed').press('ArrowRight');
  assert.deepEqual(await page.locator('#review-scroll').evaluate(e=>({top:e.scrollTop,html:e.innerHTML})),beforeExport);
  await page.locator('#width-precomputed').click();
  await page.locator('#export-toggle').click();
  const gaps=await page.locator('.ladder-row').first().locator('.sample').evaluateAll(es=>es.slice(1).map((e,i)=>e.getBoundingClientRect().top-es[i].getBoundingClientRect().bottom));
  assert(gaps.every(gap=>gap>=0&&gap<=8),`Size samples should be closely stacked: ${gaps}`);
  await page.locator('#outlines-tab').click();
  assert.equal(await page.locator('#glyphs').isVisible(),true);
  assert.equal(await page.locator('.previews').isVisible(),false);
  await page.locator('#export-toggle').click();
  await page.locator('#width-javascript').click();
  assert((await page.locator('#export').textContent()).includes('<script>'));
  await page.locator('#width-javascript').press('ArrowRight');
  assert.equal(await page.locator('#width-none').getAttribute('aria-selected'),'true');
  assert(!(await page.locator('#export').textContent()).includes('<script>'));
  await page.locator('#width-precomputed').click();
  await page.locator('#tracking-out').fill('0.06');
  await page.locator('#tracking-out').press('Enter');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Loaded'));
  await page.locator('#preview-tab').click();
  const widths=await page.locator('#size-ladder > .ladder-row:first-child .ladder-transformed .sc-rest').first().evaluate(e=>[e.getBoundingClientRect().width,e.parentElement.getBoundingClientRect().width]);
  assert(Math.abs(widths[0]-widths[1])<.1,'Switching views must preserve measurable previews');
  await page.locator('#sidebar').evaluate(e=>e.scrollTop=0);
  await page.locator('#export-toggle').click();
  await page.screenshot({path:'/tmp/smallcaps-app-desktop.png'});
  await page.locator('#research-tab').click();
  assert.equal(await page.locator('#corpus-plot').isVisible(),true);
  await page.locator('#research-tab').press('Home');
  assert.equal(await page.locator('#preview-tab').getAttribute('aria-selected'),'true');
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.querySelector('#recipe-toggle').getAttribute('aria-expanded')==='false');
  assert.equal(await page.locator('#recipe-toggle').getAttribute('aria-expanded'),'false');
  assert.equal(await page.locator('#target').isVisible(),false);
  await page.locator('#recipe-toggle').click();
  assert.equal(await page.locator('#target').isVisible(),true);
  await page.locator('#recipe-toggle').press('Enter');
  assert.equal(await page.locator('#target').isVisible(),false);
  await page.setViewportSize({width:1440,height:1000});
  await page.waitForFunction(()=>document.querySelector('#recipe-toggle').getAttribute('aria-expanded')==='true');
  assert.equal(await page.locator('#target').isVisible(),true);
  assert.equal(await page.locator('#recipe-toggle').isVisible(),false);
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.querySelector('#recipe-toggle').getAttribute('aria-expanded')==='false');
  assert.equal(await page.locator('#target').isVisible(),false);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight));
  await page.locator('#export-toggle').click();
  await page.locator('#transform-width-mode').scrollIntoViewIfNeeded();
  await page.screenshot({path:'/tmp/smallcaps-app-mobile.png'});
  assert.deepEqual(errors,[]);
  console.log('Application layout passed: independent desktop panes, view tabs, export tabs, keyboard navigation, mobile flow.');
  await browser.close();
})().catch(async error=>{console.error(error);await browser?.close();process.exitCode=1;});
