const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
let browser;
(async()=>{
  browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  await page.goto(pathToFileURL(path.resolve('index.html')).href);
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready.'));
  const load=async file=>{
    await page.locator('#upload').setInputFiles(file);
    await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Loaded'));
  };
  await load('fonts/SourceSans3.ttf');
  assert.equal(await page.locator('#comparison-size-tab').getAttribute('aria-selected'),'true');
  assert.equal(await page.locator('#overlay-comparison').isVisible(),false);
  await page.locator('#comparison-overlay-tab').click();
  const selection=()=>page.locator('#overlay-preview .overlay-sample').evaluateAll(es=>es.map(e=>e.dataset.overlaySource));
  assert.deepEqual(await selection(),['transformed','native']);
  assert.equal(await page.locator('#size-comparison').isVisible(),false);
  const rest=await page.locator('#overlay-preview .sc-rest').evaluate(e=>({visible:e.getBoundingClientRect().width,reserved:e.parentElement.getBoundingClientRect().width}));
  assert(Math.abs(rest.visible-rest.reserved)<.1);
  const baselines=await page.locator('#overlay-preview .overlay-sample').evaluateAll(es=>es.map(e=>{
    const marker=document.createElement('span');marker.style.cssText='display:inline-block;width:0;height:0;vertical-align:baseline';e.append(marker);
    const top=marker.getBoundingClientRect().top;marker.remove();return top;
  }));
  assert(Math.abs(baselines[0]-baselines[1])<.1,'Overlay layers share a baseline');
  await page.locator('#overlay-comparison').screenshot({path:'/tmp/smallcaps-overlay.png'});
  await page.locator('#comparison-size-tab').click();
  await page.locator('[data-preview-toggle="native"]').uncheck();
  await page.locator('#comparison-overlay-tab').click();
  assert.deepEqual(await selection(),['calibrated','transformed']);
  await page.locator('#comparison-size-tab').click();
  await page.locator('[data-preview-toggle="native"]').check();
  await page.locator('#comparison-overlay-tab').click();
  assert.deepEqual(await selection(),['transformed','native']);
  await page.locator('#overlay-first').selectOption('calibrated');
  await page.locator('#size').evaluate(e=>{e.value=40;e.dispatchEvent(new Event('input',{bubbles:true}));});
  assert.deepEqual(await selection(),['calibrated','native']);
  assert.deepEqual(await page.locator('#overlay-preview .overlay-sample').evaluateAll(es=>es.map(e=>getComputedStyle(e).fontSize)),['40px','40px']);
  await page.locator('#overlay-second').selectOption('calibrated');
  assert.equal(new Set(await selection()).size,2);
  await page.locator('#comparison-size-tab').click();
  for(const id of ['all-caps','naive','calibrated','transformed'])await page.locator(`[data-preview-toggle="${id}"]`).uncheck();
  await page.locator('#comparison-overlay-tab').click();
  assert.equal(await page.locator('#overlay-preview').isVisible(),false);
  assert.equal(await page.locator('#overlay-first').isDisabled(),true);
  await page.locator('#comparison-size-tab').click();
  for(const id of ['all-caps','naive','calibrated','transformed'])await page.locator(`[data-preview-toggle="${id}"]`).check();
  await load('/tmp/smallcaps-no-reference.woff2');
  assert.equal(await page.locator('[data-preview-toggle="native"]').isDisabled(),true);
  await page.locator('#comparison-overlay-tab').click();
  assert.deepEqual(await selection(),['calibrated','transformed']);
  assert.equal(await page.locator('#overlay-first option[value="native"]').count(),0);
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await browser.close();
  console.log('Overlay defaults, shared baseline, manual selection, visibility, unavailable references, sizing, and mobile layout passed.');
})().catch(async error=>{console.error(error);await browser?.close();process.exitCode=1;});
