const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
let browser;
(async()=>{
  browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.resolve('index.html')).href);
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready.'));
  assert.equal(await page.locator('#sidebar #status').count(),1);
  assert.equal(await page.locator('.app-main #status, .app-main #font-summary, #font-name').count(),0);
  let release,arrived;
  const requestSeen=new Promise(resolve=>arrived=resolve),gate=new Promise(resolve=>release=resolve);
  await page.route('https://example.com/slow.ttf',async route=>{
    arrived();await gate;await route.fulfill({body:fs.readFileSync('fonts/SourceSerif4.ttf')});
  });
  await page.locator('#google-font').fill('https://example.com/slow.ttf');
  const before=await page.locator('#google-load').boundingBox();
  await page.locator('#google-load').click();await requestSeen;
  assert.equal(await page.locator('#status.is-loading').count(),1);
  assert.equal(await page.locator('#google-load.is-loading').count(),1);
  assert.equal(await page.locator('#workspace').getAttribute('aria-busy'),'true');
  assert.equal(await page.locator('#status').getAttribute('role'),'status');
  assert.deepEqual(await page.locator('#google-load').boundingBox(),before,'Loading must not move the button');
  assert.equal(await page.locator('#status').evaluate(e=>getComputedStyle(e,'::before').visibility),'visible');
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('#status').evaluate(e=>getComputedStyle(e,'::before').animationName),'none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  // A completed local import must not clear a pending download's loading state.
  await page.locator('#upload').setInputFiles('fonts/SourceSans3.ttf');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Loaded Source Sans 3'));
  assert.equal(await page.locator('#status.is-loading').count(),1);
  release();
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Loaded Source Serif 4')&&!document.querySelector('#status').classList.contains('is-loading'));
  assert.equal(await page.locator('#google-load.is-loading').count(),0);
  assert.equal(await page.locator('#workspace').getAttribute('aria-busy'),null);
  assert.equal(await page.locator('#sidebar #font-summary').count(),1);
  assert.equal(await page.locator('#font-summary').evaluate(e=>e.open),false);
  await page.locator('#font-summary summary').click();
  assert.match(await page.locator('#smcp-support').innerText(),/Native small-caps \(smcp\): yes/);
  assert.doesNotMatch(await page.locator('#smcp-support').innerText(),/Loaded file|Source Serif/);
  assert.equal(await page.getByRole('textbox',{name:'Sample text',exact:true}).count(),1);
  assert.match(await page.locator('#sample').getAttribute('title'),/Uppercase words/);
  assert.equal(await page.locator('#size-comparison #preview-lines').count(),1);
  assert((await page.locator('#preview-lines').boundingBox()).height<80,'Show lines stays compact');
  assert.equal(await page.locator('#comparison-size-tab').getAttribute('aria-selected'),'true');
  await page.locator('#comparison-size-tab').focus();await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator(':focus').getAttribute('id'),'comparison-overlay-tab');
  assert.equal(await page.locator('#preview-lines').isVisible(),false);
  assert.equal(await page.locator('#overlay-comparison').isVisible(),true);
  const checkWidths=async selector=>{
    const widths=await page.locator(selector).evaluateAll(es=>es.map(e=>[e.getBoundingClientRect().width,e.parentElement.getBoundingClientRect().width]));
    assert(widths.length>0);assert(widths.every(([visible,reserved])=>visible>0&&Math.abs(visible-reserved)<.2),JSON.stringify(widths));
  };
  await checkWidths('#overlay-preview .sc-rest');
  await page.locator('#scale').evaluate(e=>{e.value=.75;e.dispatchEvent(new Event('input',{bubbles:true}));});
  await checkWidths('#overlay-preview .sc-rest');
  await page.locator('#comparison-overlay-tab').focus();await page.keyboard.press('Home');
  assert.equal(await page.locator(':focus').getAttribute('id'),'comparison-size-tab');
  await checkWidths('#size-ladder .sc-rest');
  await page.keyboard.press('End');await checkWidths('#overlay-preview .sc-rest');
  await page.keyboard.press('ArrowLeft');
  await page.locator('[data-preview-toggle="native"]').uncheck();
  const load=async file=>{
    await page.locator('#upload').setInputFiles(file);
    await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Loaded')&&!document.querySelector('#status').classList.contains('is-loading'));
  };
  await load('/tmp/smallcaps-no-reference.woff2');
  const native=page.locator('[data-preview-toggle="native"]');
  assert.equal(await native.isDisabled(),true);
  assert.equal(await page.locator('#native-toggle-label').textContent(),'Built-in (unavailable for this font)');
  assert.equal(await page.locator('.ladder-native').count(),0);
  assert.equal(await page.locator('#overlay-first option[value="native"]').count(),0);
  await load('fonts/InterVariable.woff2');
  assert.equal(await native.isDisabled(),true,'Phonetic references do not imply native smcp');
  await page.locator('#comparison-overlay-tab').click();
  assert.equal(await page.locator('#overlay-preview .reference-glyph').count(),22);
  await page.locator('#comparison-size-tab').click();
  await load('fonts/SourceSans3.ttf');
  assert.equal(await native.isDisabled(),false);
  assert.equal(await native.isChecked(),false,'Availability preserves the visibility preference');
  assert.equal(await page.locator('#native-toggle-label').textContent(),'Built-in');
  await native.check();assert.equal(await page.locator('.ladder-native:visible').count(),10);
  await page.route('https://example.com/failure.ttf',r=>r.abort());
  await page.locator('#google-font').fill('https://example.com/failure.ttf');await page.locator('#google-font').press('Enter');
  await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));
  assert.equal(await page.locator('#status.is-loading, #google-load.is-loading').count(),0);
  assert.equal(await page.locator('#workspace').getAttribute('aria-busy'),null);
  assert.equal(await page.locator('#google-load').isDisabled(),false);
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('UI state passed: loading/error cleanup, concurrent loads, reduced motion, sidebar details, comparison tabs, width measurement, and Built-in availability.');
})().catch(async error=>{console.error(error);await browser?.close();process.exitCode=1;});
